"""
Shared Excel export helpers used by every report/dashboard export endpoint.

Centralizes header styling, generic row -> sheet rendering, an auto-KPI
"Summary" sheet, and workbook streaming so every export (existing and new)
is visually consistent and carries the same auto-computed summary.
"""
import io
import uuid
from datetime import datetime
from decimal import Decimal

from fastapi.responses import StreamingResponse

_HDR_FILL_COLOR = "0C0D10"


def style_header(ws, cols: list, row: int = 1) -> None:
    import openpyxl.styles as xs
    fill = xs.PatternFill("solid", fgColor=_HDR_FILL_COLOR)
    font = xs.Font(bold=True, color="FFFFFF")
    for ci, col in enumerate(cols, 1):
        cell = ws.cell(row=row, column=ci, value=col)
        cell.fill = fill
        cell.font = font


def _cell_value(val):
    if isinstance(val, uuid.UUID):
        # openpyxl only accepts str/number/date/bool/None -- psycopg2 returns
        # UUID columns as uuid.UUID objects (register_uuid() in db.py), and
        # any export sheet that includes a raw id/*_id column (recent_reqs,
        # gender_split, enteri_ai_recent, recruiter_load, ...) previously 500'd
        # here with "Cannot convert UUID(...) to Excel" -- this one helper is
        # shared by every Excel export in the app, so this single fix covers
        # all of them at once.
        return str(val)
    if isinstance(val, Decimal):
        val = float(val)
    if isinstance(val, float) and val.is_integer():
        return int(val)
    if isinstance(val, datetime) and val.tzinfo is not None:
        # openpyxl/Excel cells can't hold tz-aware datetimes — psycopg2 returns
        # TIMESTAMPTZ columns as tz-aware, so strip tzinfo (keep the wall-clock
        # value; DB connections are UTC) rather than crash the whole export.
        return val.replace(tzinfo=None)
    if isinstance(val, (list, tuple, dict, set)):
        # A JSONB/array column (e.g. key_skills TEXT[], screening_questions)
        # landing in an export sheet -- openpyxl rejects these container
        # types outright, same failure mode as UUID above.
        return str(val)
    return val


def _get(row, key):
    return row.get(key) if isinstance(row, dict) else getattr(row, key, None)


def sheet_from_rows(wb, title: str, rows: list, columns: list | None = None):
    """
    columns: optional [(label, key), ...] to control order/labels — matches
    hiring_plan_api's _EXCEL_COLS shape. Without it, columns are derived
    from rows[0].keys() — matches the existing generic pivot behavior.
    """
    ws = wb.create_sheet(title=title[:31])
    if not rows:
        ws.cell(1, 1, "No data")
        return ws
    if columns:
        labels, keys = [c[0] for c in columns], [c[1] for c in columns]
    else:
        keys = list(rows[0].keys())
        labels = keys
    style_header(ws, labels)
    for ri, row in enumerate(rows, 2):
        for ci, key in enumerate(keys, 1):
            ws.cell(ri, ci, _cell_value(_get(row, key)))
    return ws


def _is_numeric(val) -> bool:
    return isinstance(val, (int, float, Decimal)) and not isinstance(val, bool)


def _numeric_columns(rows: list) -> list:
    """Auto-detect numeric columns, skipping id / *_id columns."""
    if not rows:
        return []
    first = rows[0]
    keys = list(first.keys()) if isinstance(first, dict) else list(vars(first).keys())
    numeric = []
    for k in keys:
        if k == "id" or k.endswith("_id"):
            continue
        sample = next((_get(row, k) for row in rows if _get(row, k) is not None), None)
        if _is_numeric(sample):
            numeric.append(k)
    return numeric


def build_summary_sheet(
    wb,
    *,
    title: str,
    generated_by: str,
    generated_at,
    filters_applied: list | None = None,
    rows: list | None = None,
    measures_meta: list | None = None,
) -> None:
    """
    Inserts a "Summary" sheet as the FIRST sheet. Purely additive — never
    renames or removes any other sheet, so this is safe to retrofit onto
    existing exports without breaking downstream consumers.
    """
    ws = wb.create_sheet("Summary", 0)
    rows = rows or []

    r = 1
    for label, value in [
        ("Report", title),
        ("Generated At", str(generated_at)),
        ("Generated By", generated_by or ""),
        ("Row Count", len(rows)),
    ]:
        ws.cell(r, 1, label)
        ws.cell(r, 2, value)
        r += 1

    filters_applied = filters_applied or []
    ws.cell(r, 1, "Filters Applied")
    if filters_applied:
        parts = [
            f"{f.get('key')} {f.get('op', '')} {f.get('value')}".strip()
            if isinstance(f, dict) else str(f)
            for f in filters_applied
        ]
        ws.cell(r, 2, "; ".join(parts))
    else:
        ws.cell(r, 2, "None")
    r += 2

    if not rows:
        ws.cell(r, 1, "No data for this report.")
        return

    auto_numeric = _numeric_columns(rows)
    if measures_meta:
        meta_keys = [m["key"] for m in measures_meta if m.get("key") in auto_numeric]
        label_by_key = {m["key"]: m.get("label", m["key"]) for m in measures_meta}
        numeric_cols = [(label_by_key[k], k) for k in meta_keys] or [(k, k) for k in auto_numeric]
    else:
        numeric_cols = [(k, k) for k in auto_numeric]

    if numeric_cols:
        style_header(ws, ["Metric", "Total", "Average", "Min", "Max"], row=r)
        r += 1
        for label, key in numeric_cols:
            vals = [float(_get(row, key)) for row in rows if _is_numeric(_get(row, key))]
            if not vals:
                continue
            ws.cell(r, 1, label)
            ws.cell(r, 2, round(sum(vals), 2))
            ws.cell(r, 3, round(sum(vals) / len(vals), 2))
            ws.cell(r, 4, round(min(vals), 2))
            ws.cell(r, 5, round(max(vals), 2))
            r += 1
        r += 1

        # Top-5 rows by the first numeric column, labeled by the first non-numeric column
        if len(rows) > 1:
            metric_label, metric_key = numeric_cols[0]
            first_row = rows[0]
            all_keys = list(first_row.keys()) if isinstance(first_row, dict) else list(vars(first_row).keys())
            numeric_keys = {k for _, k in numeric_cols}
            label_key = next((k for k in all_keys if k not in numeric_keys), None)
            if label_key:
                top_rows = sorted(
                    rows,
                    key=lambda row: float(_get(row, metric_key)) if _is_numeric(_get(row, metric_key)) else float("-inf"),
                    reverse=True,
                )[:5]
                style_header(ws, [f"Top 5 by {metric_label}", metric_label], row=r)
                r += 1
                for row in top_rows:
                    ws.cell(r, 1, _cell_value(_get(row, label_key)))
                    ws.cell(r, 2, _cell_value(_get(row, metric_key)))
                    r += 1


def stream_workbook(wb, filename: str) -> StreamingResponse:
    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
